### ISSUE TITLE
Horizontal Scaling

### ISSUE THREAD

**Issue by MoonTahoe** [MoonHighway/moonhighway-cloud#1]
We want to be able to start several instances of  each of the cloud services. In order to do this we need to make sure each service is using an actual database instead of memory or a file system.

## Tasks

- [ ] Add Database for Color Service
- [ ] Start all services with PM2
- [ ] Configure PM2 commands with Node js

**Comment by MoonTahoe** [comment]
We may not need to do this. It might make more sense to get away from databases entirely. see #3.
