### ISSUE TITLE
User Interface for the Hue Review

### ISSUE THREAD

**Issue by MoonTahoe** [MoonHighway/moonhighway-cloud#7]
We have an api, now we need a website. Just in time for Apollo Client 3. The Hue Review will allow users to add their favorite colors and rate them. 

Right now `create-react-app` was run awhile ago on the project's folder: [./ui-hue-review](https://github.com/MoonHighway/moonhighway-cloud/tree/master/ui-hue-review). The dependencies need to be updated and the Apollo Client 3 needs to be incorporated. The API url for the Hue Review is `http://localhost:4000`.

## Don't start from scratch

In the Book [Learning React](https://github.com/MoonHighway/learning-react), we [Color Organizer](https://codesandbox.io/s/learning-react-color-organizer-9-ypf8r?file=/src/ColorList.js). This application has many of the
same features that we are looking for in the UI. It has components for Colors, and a form for adding colors. 

## Tasks

- [ ] Create Issues for getting started
- [ ] Create Issues for building each feature

## Features

- [ ] Anyone can view and surf for colors
- [ ] Each Color displays the user who posted that color
- [ ] Each Color displays the adv rating for the color
- [ ] Each Color displays each review. 
- [ ] Users can create accounts
- [ ] Users can login/logout
- [ ] Users can add new colors
- [ ] Users can review colors
- [ ] UI Starts up with overall project
