### ISSUE TITLE
Review Manager CLI

### ISSUE THREAD

**Issue by MoonTahoe** [MoonHighway/moonhighway-cloud#8]
Internal Admins need to be able to manage the review application and it's data. These guys are engineers, so we decided to make this tool a CLI. 

## Tasks

- [ ] Organize Initial Project Setup Issues
- [ ] Create Issues and Plan for Each Feature

## Features

- [ ] Administrators can log in/log out 
- [ ] Administrators can create accounts for other administrators
- [ ] Administrators can list, sort, and filter all review data
- [ ] Administrators can remove a review, or reviews by associated data
- [ ] Administrators can reset all review data
- [ ] Administrators can backup all review data
